### ISSUE TITLE
PROJ.4 datum grids are missing

### ISSUE THREAD

**Issue by edzer** [rwinlib/gdal2#2]
To convert to and from national grids (datums), PROJ.4 needs to have the grid definitions. These are currently not part of this distribution. They are part of the rgdal package, so need to get in here too. The grids are found in this file:

http://download.osgeo.org/proj/proj-datumgrid-1.6.zip

and need to be unpacked in directory gdal2-2.1.1/share/proj/

In future builds of this package, before configuring PROJ.4 this file should be unpacked in the proj-x.y.z/nad directory (x.y.z now being 4.9.3), installing PROJ.4 would copy over the files to the right place.

**Comment by jeroen** [comment]
Can you send a PR?

**Comment by edzer** [comment]
Done!

**Comment by jeroen** [comment]
OK it's merged. I also moved the `v2.1.1` tag to `HEAD` so that you can keep using the same download URL.

**Comment by edzer** [comment]
I checked and everything worked out for sf 0.2-7 on CRAN, and appveyor. Thanks, Jeroen!

**Comment by jeroen** [comment]
Good to know, thanks.

**Comment by edzer** [comment]
The files I added in https://github.com/rwinlib/gdal2/commit/43f7368d616be4699f744970445c6a8ce9750448 are again missing from `share/proj`. Shall I add them in a new PR?

**Comment by jeroen** [comment]
@edzer ah that explains it, i'm sorry. Are these files not included with proj? The build script just replaced the entire `/share/proj` dir with the latest one I guess.

**Comment by jeroen** [comment]
@edzer I have re-applied your commit to head. Can you try to trigger a rebuild of `sf` ?

**Comment by edzer** [comment]
Thanks, will do!

@rsbivand I'm not sure now whether we should copy over the old files (like `conus`) or those in http://download.osgeo.org/proj/proj-datumgrid-1.5.zip which all have the `.lla` extension (`conus.lla`).

**Comment by edzer** [comment]
@jeroen this worked out!

**Comment by jeroen** [comment]
So everything is good now? I still see some diff's in the check but those are expected?

**Comment by edzer** [comment]
Yes, these diffs are all expected.
