### ISSUE TITLE
GDAL WFS driver needs curl support

### ISSUE THREAD

**Issue by rsbivand** [rwinlib/gdal2#5]
Hi Jeroen!

I've been contacted by Joona Lehtomäki of [rwfs](https://github.com/rOpenGov/rwfs) who can use GDAL on non-Windows platforms:

> The problem is, that the current binary distribution of rgdal for Windows does not have the WFS driver enabled as shown by ogrDrivers()$name. The Linux distributions I've tested on so far, have GDAL with the WFS driver enabled so there are no issues with rgdal either (it being a source installation). This seems to be the case for Mac too, at least if some system-wide libraries are installed through Macports (I can't say for sure for the binary since I have no access to a Mac, but see e.g. [2] and [3] for more details on platforms,
installation types and versions used). To be more precise, e.g. the command works on Linux and Mac (at least the tested configurations), but not on Windows:
QUESTION: in the future, is there any possibility to have the WFS driver enabled in the version of GDAL shipped with the binary distribution of rgdal on Windows? I understand that enabling more drivers may incur costs in terms of complexity and size of the build, but wanted to ask before deciding what to do with our own package.

I think that the Windows binaries for sf and rgdal could provide the WFS driver if GDAL was built with curl support - see: [WFS](http://www.gdal.org/drv_wfs.html).

I hope Joona will join in.

Best wishes,

Roger

**Comment by jlehtoma** [comment]
Thanks @rsbivand for opening up the issue here. [Here's our use case](https://github.com/rOpenGov/rwfs/issues/4) requiring WFS driver on Windows if it's of any help. Also happy to help any other way I can.

**Comment by jeroen** [comment]
Can you provide a minimal reproducible example that I can use to test if it works?

**Comment by jlehtoma** [comment]
Sure:

```r
# Demo WFS server
wfs_ds <- "WFS:http://demo.mapserver.org/cgi-bin/wfs"

# Works on Linux
> rgdal::ogrListLayers(wfs_ds) 
[1] "continents" "cities"    
attr(,"driver")
[1] "WFS"
attr(,"nlayers")
[1] 2

# Fails on Windows
> rgdal::ogrListLayers(wfs_ds) 
Error in rgdal::ogrListLayers(wfs_ds) : Cannot open data source
```

## Enabled GDAL drivers

### Linux

```r
> rgdal::ogrDrivers()$name
 [1] "AeronavFAA"     "AmigoCloud"     "ARCGEN"         "AVCBin"         "AVCE00"        
 [6] "BNA"            "Carto"          "Cloudant"       "CouchDB"        "CSV"           
[11] "CSW"            "DGN"            "DXF"            "EDIGEO"         "ElasticSearch" 
[16] "ESRI Shapefile" "Geoconcept"     "GeoJSON"        "Geomedia"       "GeoRSS"        
[21] "GFT"            "GML"            "GPKG"           "GPSBabel"       "GPSTrackMaker" 
[26] "GPX"            "HTF"            "HTTP"           "Idrisi"         "Interlis 1"    
[31] "Interlis 2"     "JML"            "JP2OpenJPEG"    "KML"            "MapInfo File"  
[36] "Memory"         "MSSQLSpatial"   "MySQL"          "NAS"            "netCDF"        
[41] "ODBC"           "ODS"            "OGR_GMT"        "OGR_PDS"        "OGR_SDTS"      
[46] "OGR_VRT"        "OpenAir"        "OpenFileGDB"    "OSM"            "PCIDSK"        
[51] "PDF"            "PGDUMP"         "PGeo"           "PLSCENES"       "PostgreSQL"    
[56] "REC"            "S57"            "SEGUKOOA"       "SEGY"           "Selafin"       
[61] "SQLite"         "SUA"            "SVG"            "SXF"            "TIGER"         
[66] "UK .NTF"        "VDV"            "VFK"            "Walk"           "WAsP"          
[71] "WFS"            "XLS"            "XLSX"           "XPlane"   
```

### Windows

```r
> rgdal::ogrDrivers()$name
 [1] "AeronavFAA"     "ARCGEN"         "AVCBin"         "AVCE00"         "BNA"            "CSV"           
 [7] "DGN"            "DXF"            "EDIGEO"         "ESRI Shapefile" "Geoconcept"     "GeoJSON"       
[13] "Geomedia"       "GeoRSS"         "GML"            "GPKG"           "GPSBabel"       "GPSTrackMaker" 
[19] "GPX"            "HTF"            "Idrisi"         "JML"            "KML"            "MapInfo File"  
[25] "Memory"         "MSSQLSpatial"   "ODBC"           "ODS"            "OGR_GMT"        "OGR_PDS"       
[31] "OGR_SDTS"       "OGR_VRT"        "OpenAir"        "OpenFileGDB"    "OSM"            "PCIDSK"        
[37] "PDF"            "PGDUMP"         "PGeo"           "REC"            "S57"            "SEGUKOOA"      
[43] "SEGY"           "Selafin"        "SQLite"         "SUA"            "SVG"            "SXF"           
[49] "TIGER"          "UK .NTF"        "Walk"           "WAsP"           "VFK"            "XLSX"          
[55] "XPlane"  
```

## System setup

### Linux

```r
> library(rgdal)
Loading required package: sp
rgdal: version: 1.2-5, (SVN revision 648)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.1.3, released 2017/20/01
 Path to GDAL shared files: /usr/share/gdal
 Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
 Path to PROJ.4 shared files: (autodetected)
 Linking to sp version: 1.2-3 

> devtools::session_info()
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language en_US                       
 collate  fi_FI.UTF-8                 
 tz       Europe/Amsterdam            
 date     2017-02-14                  

Packages --------------------------------------------------------------------------------------
 package  * version     date       source                          
 crayon     1.3.2       2016-06-28 CRAN (R 3.3.1)                  
 devtools * 1.12.0.9000 2017-02-13 Github (hadley/devtools@d8ab190)
 digest     0.6.12      2017-01-27 CRAN (R 3.3.2)                  
 lattice    0.20-34     2016-09-06 CRAN (R 3.3.2)                  
 magrittr   1.5         2014-11-22 CRAN (R 3.3.0)                  
 memoise    1.0.0       2016-01-29 CRAN (R 3.3.0)                  
 pkgbuild   0.0.0.9000  2017-02-13 Github (r-pkgs/pkgbuild@65eace0)
 pkgload    0.0.0.9000  2017-02-13 Github (r-pkgs/pkgload@fc907a1) 
 R6         2.2.0       2016-10-05 cran (@2.2.0)                   
 rgdal    * 1.2-5       2016-12-15 CRAN (R 3.3.2)                  
 sp       * 1.2-4       2016-12-22 cran (@1.2-4)                   
 testthat * 1.0.2       2016-04-23 CRAN (R 3.3.0)                  
 withr      1.0.2       2016-06-20 CRAN (R 3.3.0)      
```

### Windows

```r
> library(rgdal)
Loading required package: sp
rgdal: version: 1.2-5, (SVN revision 648)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.0.1, released 2015/09/15
 Path to GDAL shared files: C:/Users/jlehtoma/Documents/R/win-library/3.3/rgdal/gdal
 Loaded PROJ.4 runtime: Rel. 4.9.2, 08 September 2015, [PJ_VERSION: 492]
 Path to PROJ.4 shared files: C:/Users/jlehtoma/Documents/R/win-library/3.3/rgdal/proj
 Linking to sp version: 1.2-4 

> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  Finnish_Finland.1252        
 tz       Europe/Berlin               
 date     2017-02-14                  

Packages -----------------------------------------------------------------------------------------------------------------
 package  * version date       source        
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest     0.6.12  2017-01-27 CRAN (R 3.3.2)
 lattice    0.20-34 2016-09-06 CRAN (R 3.3.2)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.2)
 rgdal    * 1.2-5   2016-12-15 CRAN (R 3.3.2)
 sp       * 1.2-4   2016-12-22 CRAN (R 3.3.2)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)
```

**Comment by rsbivand** [comment]
I think that it can be resolved by pointing GDAL at curl when it is built, then probably adding curl to PKG_LIBS.

**Comment by jeroen** [comment]
Yeah but do note that libcurl depends on several other [libs](https://github.com/jeroenooms/curl/blob/master/src/Makevars.win#L5-L7) so this makes your stack significantly heavier. And it already is pretty heavy.

**Comment by rsbivand** [comment]
Could @edzer  please give a view on this?

**Comment by jeroen** [comment]
Also currently `rgdal` does not use the libs from this repo, correct? Maybe you can try and test what `rgdal::ogrDrivers()$name` if you try and link to this repo on Windows. Chances are that might already work ....

**Comment by rsbivand** [comment]
sf doesn't have the WFS driver - on Windows from CRAN, rgdal and sf have the same drivers (I believe but didn't check that they match exactly - both had 56 drivers and neither had WFS).

**Comment by edzer** [comment]
The binary macos version of `sf` and `rgdal` both have the WFS driver.

It would be excellent to have WFS in in the windows GDAL binary port. I have so far never heard complaints about rgdal (or sf) being heavy. Having an everything-reader is just too good.

**Comment by jlehtoma** [comment]
@jeroenooms : any plans to move ahead with this? If not, I'll need to come up with an alternative solution. Apologies if I misunderstood something, I'm not familiar at all on `GDAL`/`rgdal` build and deployment system.

**Comment by jlehtoma** [comment]
Still getting back to this as the only options right now on Windows is to use `ogr2ogr` which has turned out to be really cumbersome for the users. Pretty please?

**Comment by jeroen** [comment]
I'll try to have a look at this soon. Rebuilding the stack is a day or two of work and a bit tricky to get it right so I need to make some time for it.

**Comment by jeroen** [comment]
Version 2.2.0 now contains support for libcurl and postgres.

**Comment by edzer** [comment]
This is great Jeroen, on behalf of the r-spatial windows community a big thanks!!

**Comment by jeroen** [comment]
You should test it first ;)

**Comment by jeroen** [comment]
Actually I am unsure how gdal deals with SSL certificates for HTTPs connections. Can you please test if this now works with https WSF connections, or if you get a cert error? I could easily tweak it so that it uses windows native SSL if that is easier.

**Comment by jeroen** [comment]
@rsbivand if you want to use these builds in `rgdal`, all you have to do is copy over [`Makevars.win`](https://github.com/r-spatial/sf/blob/master/src/Makevars.win) and [`tools/winlibs.R`](https://github.com/r-spatial/sf/blob/master/tools/winlibs.R) from the sf package. It will work out of the box without having to bother CRAN.

**Comment by edzer** [comment]
I hope @jlehtoma will be able to check this. 

Things pass check for sf on [appveyor](https://ci.appveyor.com/project/r-spatial/sf), but give numerical differences -- did you make sure to copy over the datum files, as described in https://github.com/rwinlib/gdal2/issues/2 ?

**Comment by jeroen** [comment]
I updated the datum files from `proj` and `gdal` to those included with the latest version...

**Comment by jeroen** [comment]
Do you see numeric differences for both x86 and x64?

**Comment by edzer** [comment]
Did you copy them over from the previous rwinlib/gdal2, or install from a new proj.4 release?

**Comment by jeroen** [comment]
From the new `proj` and `gdal` releases.

**Comment by edzer** [comment]
Thanks, that might be the other explanation; will try to find out.

**Comment by jeroen** [comment]
I assume these binary files have to be in sync with the library version?

**Comment by edzer** [comment]
I don't think so, but they should be kept together - they don't have their own versioning system.

**Comment by jeroen** [comment]
Ah ok. But I suppose on e.g. Linux sf also uses the datum files included with the library version? Or are you shipping you own?

**Comment by jeroen** [comment]
Can you give an example of a function that returns a different result? I can try to help debugging.

**Comment by edzer** [comment]
```r
library(sf)
x = st_sfc(st_point(c(-90,35)), st_point(c(-80,36)), crs = "+proj=longlat +datum=NAD27")
st_transform(x, 3857)
# Geometry set for 2 features
# geometry type:  POINT
# dimension:      XY
# bbox:           xmin: -10018760 ymin: 4163894 xmax: -8905533 ymax: 4300640
# epsg (SRID):    3857
# proj4string:    +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs
# POINT(-10018764.3099097 4163893.70169306)
# POINT(-8905532.70139521 4300640.2154045)

# new rwinlib/gdal2 gives the following diff on `tests/sfc.Rout.save`:

364,365c362,363
< POINT(-10018754.1713946 4163881.14406429)
< POINT(-8905559.26346189 4300621.37204427)
---
> POINT(-10018764.3099097 4163893.70169306)
> POINT(-8905532.70139521 4300640.2154045)
```

I think I've seen it before, and that it is not because of proj.4 version update; 10-30 m differences are typical for datum differences.

**Comment by jeroen** [comment]
Are you sure this is a new problem? I am seeing the same output for the CRAN version as for the dev version on Windows:
```
POINT(-10018764.3099097 4163893.70169306)
POINT(-8905532.70139521 4300640.2154045)
```

**Comment by edzer** [comment]
What you copy is the right output, the new one is marked with the `<` and is wrong; I found it [here](https://ci.appveyor.com/project/edzerpebesma/sf).

The output of the diff is not seen [here](https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/sf-00check.html), indicating no differences.

**Comment by jeroen** [comment]
OK you are right these are indeed a result of the `proj.4` datum updates. Do you want me to revert the data, or will you update the unit tests?

**Comment by jlehtoma** [comment]
I certainly can test this, but unfortunately my skills are pretty limited when it comes to building things (`gdal2` and/or `rgdal`) on Windows. Unless someone has the time to describe how to get started, I would need to grab the binaries from somewhere before testing.

**Comment by jeroen** [comment]
@jlehtoma if you have the latest R and Rtools installed you can use this:

```r
devtools::install_github("jeroen/rgdal@rwinlib", subdir = "pkg")
```

**Comment by jlehtoma** [comment]
Thanks @jeroen , that worked like a charm. I'm happy to report that the update solves my issue:

```r
> library(rgdal)
Loading required package: sp
rgdal: version: 1.2-8, (SVN revision (unknown))
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.2.0, released 2017/04/28
 Path to GDAL shared files: C:/Users/jlehtoma/Documents/R/win-library/3.4/rgdal/gdal
 Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
 Path to PROJ.4 shared files: C:/Users/jlehtoma/Documents/R/win-library/3.4/rgdal/proj
 Linking to sp version: 1.2-5 
> rgdal::ogrDrivers()$name
 [1] "AeronavFAA"     "AmigoCloud"     "ARCGEN"         "AVCBin"         "AVCE00"         "BNA"            "CAD"           
 [8] "Carto"          "Cloudant"       "CouchDB"        "CSV"            "CSW"            "DGN"            "DXF"           
[15] "EDIGEO"         "ElasticSearch"  "ESRI Shapefile" "Geoconcept"     "GeoJSON"        "Geomedia"       "GeoRSS"        
[22] "GFT"            "GML"            "GPKG"           "GPSBabel"       "GPSTrackMaker"  "GPX"            "HTF"           
[29] "HTTP"           "Idrisi"         "JML"            "KML"            "MapInfo File"   "Memory"         "MSSQLSpatial"  
[36] "netCDF"         "ODBC"           "ODS"            "OGR_GMT"        "OGR_PDS"        "OGR_SDTS"       "OGR_VRT"       
[43] "OpenAir"        "OpenFileGDB"    "OSM"            "PCIDSK"         "PDF"            "PGDUMP"         "PGeo"          
[50] "PLSCENES"       "PostgreSQL"     "REC"            "S57"            "SEGUKOOA"       "SEGY"           "Selafin"       
[57] "SQLite"         "SUA"            "SVG"            "SXF"            "TIGER"          "UK .NTF"        "Walk"          
[64] "WAsP"           "VDV"            "VFK"            "WFS"            "XLS"            "XLSX"           "XPlane"   
```

and 

```r
> wfs_ds <- "WFS:http://demo.mapserver.org/cgi-bin/wfs"
# Works!
> rgdal::ogrListLayers(wfs_ds) 
[1] "continents" "cities"    
attr(,"driver")
[1] "WFS"
attr(,"nlayers")
[1] 2
```

```r
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.301)           
 language (EN)                        
 collate  Finnish_Finland.1252        
 tz       Europe/Berlin               
 date     2017-07-11                  

Packages ---------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                       
 base      * 3.4.1   2017-06-30 local                        
 compiler    3.4.1   2017-06-30 local                        
 datasets  * 3.4.1   2017-06-30 local                        
 devtools    1.13.2  2017-06-02 CRAN (R 3.4.1)               
 digest      0.6.12  2017-01-27 CRAN (R 3.4.1)               
 graphics  * 3.4.1   2017-06-30 local                        
 grDevices * 3.4.1   2017-06-30 local                        
 grid        3.4.1   2017-06-30 local                        
 lattice     0.20-35 2017-03-25 CRAN (R 3.4.1)               
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.1)               
 methods   * 3.4.1   2017-06-30 local                        
 rgdal     * 1.2-8   2017-07-11 Github (jeroen/rgdal@498258b)
 sp        * 1.2-5   2017-06-29 CRAN (R 3.4.1)               
 stats     * 3.4.1   2017-06-30 local                        
 tools       3.4.1   2017-06-30 local                        
 utils     * 3.4.1   2017-06-30 local                        
 withr       1.0.2   2016-06-20 CRAN (R 3.4.1)
```

**Comment by jeroen** [comment]
@jlehtoma do you know of any WFS servers that run on HTTPS so that I can test the SSL support?

**Comment by jlehtoma** [comment]
(EDIT: API-key removed)

The only one I was able to find so far is one for the Finnish Meteorological Institute (FMI) WFS. Unfortunately it needs [a personal API-key](http://en.ilmatieteenlaitos.fi/open-data-manual). The URL below contains mine, I'll delete it once it's not needed here anymore. The query should return an average temperature for 22 weather stations in Southern Finland within the specified time period. 
```r
URL <- "data.fmi.fi/fmi-apikey/XXXXX-XXXXX/wfs?request=getFeature&storedquery_id=fmi::observations::weather::daily::timevaluepair&starttime=2014-01-01&endtime=2014-01-01&bbox=23.5,59.7,26.5,60.7&parameters=tday"
wfs_ds_http <- paste0("http://", URL)
wfs_ds_https <- paste0("https://", URL)
```
Testing `rgdal::readOGR()` on Windows with the latest build gives the following:

```r
# HTTP - works
> sp_wfs <- rgdal::readOGR(wfs_ds_http) 
OGR data source with driver: GML 
Source: "http://data.fmi.fi/fmi-apikey/XXXXX-XXXXX/wfs?request=getFeature&storedquery_id=fmi::observations::weather::daily::timevaluepair&starttime=2014-01-01&endtime=2014-01-01&bbox=23.5,59.7,26.5,60.7&parameters=tday", layer: "PointTimeSeriesObservation"
with 22 features
It has 10 fields, of which 1 list fields
```
and 
```r
# HTTPS - does not work
> sp_wfs <- rgdal::readOGR(wfs_ds_https)
Error in ogrListLayers(dsn = dsn) : Cannot open data source
```

On Linux, both work fine.

**Comment by jeroen** [comment]
@jlehtoma thanks that is very helpful. I updated the gdal stack to use windows ssl. Can you try to reinstall and check if it works now:

```r
devtools::install_github("jeroen/rgdal@rwinlib", subdir = "pkg", force = TRUE)
```

**Comment by jlehtoma** [comment]
(EDIT: API-key removed)

After updating, HTTPS works too :champagne: 

```r
> sp_wfs_http <- rgdal::readOGR(wfs_ds_http) 
OGR data source with driver: GML 
Source: "http://data.fmi.fi/fmi-apikey/XXXXX-XXXXX/wfs?request=getFeature&storedquery_id=fmi::observations::weather::daily::timevaluepair&starttime=2014-01-01&endtime=2014-01-01&bbox=23.5,59.7,26.5,60.7&parameters=tday", layer: "PointTimeSeriesObservation"
with 22 features
It has 10 fields, of which 1 list fields
> sp_wfs_https <- rgdal::readOGR(wfs_ds_https) 
OGR data source with driver: GML 
Source: "https://data.fmi.fi/fmi-apikey/XXXXX-XXXXX/wfs?request=getFeature&storedquery_id=fmi::observations::weather::daily::timevaluepair&starttime=2014-01-01&endtime=2014-01-01&bbox=23.5,59.7,26.5,60.7&parameters=tday", layer: "PointTimeSeriesObservation"
with 22 features
It has 10 fields, of which 1 list fields
> identical(sp_wfs_http, sp_wfs_https)
[1] TRUE
```

**Comment by jeroen** [comment]
OK perfect. Thanks for your help!

**Comment by jlehtoma** [comment]
Thank *you* for making this work!

**Comment by edzer** [comment]
When I point `PROJ_LIB` to an empty directory, I can reproduce the diffs I see above. @jeroen could you give me the directory listing of the directory obtained by
```r
system.file("proj", package = "sf")
```
after installing `sf` from GH on your computer?

**Comment by rsbivand** [comment]
Right, no extra files in rgdal/proj from winbuilder either, just the basic ones. So NAD27 converted without the grid files. This is curious, as installed PROJ.4 4.9.3 bundles all the files for share/proj now, so maybe copied from the older proj?

**Comment by jeroen** [comment]
@rsbivand this should now be solved, can you try again?

**Comment by rsbivand** [comment]
Already submitted to winbuilder on seeing Edzer's [report](https://github.com/rwinlib/gdal2/issues/2#issuecomment-314699381), will get back once I receive the completion email.

**Comment by rsbivand** [comment]
Confirmed grids now present in Windows rgdal binary, thanks!

**Comment by edzer** [comment]
Great work! sf 0.5-2 now on CRAN; win build there might take a few days.
