### ISSUE TITLE
is c++11 a requirement?

### ISSUE THREAD

**Issue by edzer** [rwinlib/gdal2#6]
If I write an R package that uses rwinlib/gdal2, is it required for that package to use C++ code compiled with c++11? Users have asked for `sf` to support R 3.2.x, which would require C++ w/o c++11.

**Comment by jeroen** [comment]
Yeah that won't work. R 3.2.x on windows has gcc 4.6.3 which is too old to build most of the libs.

**Comment by jeroen** [comment]
R 3.2 is end of life in a month when R 3.4 is released. At that point CRAN will stop supporting it as well. People should just move forward and upgrade R if they want to use this. We really don't have the resources to provide legacy support for people that want to run an old version of R.

**Comment by edzer** [comment]
OK, make sense, thanks!

**Comment by jeroen** [comment]
However note that you can support R 3.2, just not on Windows :)
