### ISSUE TITLE
JPEG 2000 / OpenJPEG

### ISSUE THREAD

**Issue by edzer** [rwinlib/gdal2#7]
Would it be possible to add the JPEG 2000 driver by adding the [OpenJPEG](http://www.openjpeg.org/) library to gdal2?

This is highly desirable: for instance the Sentinel 2A and 2B satellites provide free data delivered in this format; these satellites were funded and are operated by the European space organizations.

Let me know where I can help.

**Comment by jeroen** [comment]
I'll try to have a look net week.

**Comment by jeroen** [comment]
@edzer I'll have to rebuild the entire stack. Are there other features/libs you'd like to support?

**Comment by edzer** [comment]
I've asked on [twitter](https://twitter.com/edzerpebesma/status/959819283734806530).

**Comment by JoshOBrien** [comment]
@edzer I'm not on Twitter, so can't reply there, but I too would add a vote for an HDF4 driver. (I actually came over here independently just now to ask for just that very thing. I searched first to see if it had already been requested, and was happily surprised to see that you and jeroen had just put out the call for such requests!)

**Comment by jeroen** [comment]
OK so i'll try to build with HDF4 and OpenJPEG for the next stack.

**Comment by jeroen** [comment]
Are there also drivers that are currently in there you don't need anymore?

**Comment by edzer** [comment]
Not that I know - it's a much harder question to answer!

**Comment by mdsumner** [comment]
I'd really like KEA to be available, builds on HDF5 but also requires libkea http://gdal.org/frmt_kea.html

(I don't think it's been added, but I also can't check right now). 

@pierreroudier will vouch for KEA ;)

Thanks @jeroen!

**Comment by mdsumner** [comment]
I'll add to the HDF4 chorus too, our primary target is these passive microwave data of sea ice concentration, an example file: 

```bash
wget https://seaice.uni-bremen.de/data/amsr2/asi_daygrid_swath/s6250/2017/dec/Antarctic/asi-AMSR2-s6250-20171211-v5.hdf
```

**Comment by pierreroudier** [comment]
@mdsumner thanks, I didn't want to be the token KEA fanboy :)

@jeroen Happy to provide sample files etc if need be

**Comment by jeroen** [comment]
It took me a few nights of fighting with windows but we have a [new release](https://github.com/rwinlib/gdal2/releases). The 2.2.3 stack adds drivers for  mysql, openjpeg, jasper, hdf4, and kealib as requested above.

A word of caution about the hdf4 driver. I had to do a bit of hacking in the libhdf source code to make it build on windows with mingw-w64. Eventually I got it to compile but it is basically untested (I don't think anyone has ever compiled hdf4 on mingw-w64 before). I highly recommend users to use hdf5 instead when possible, which has proper windows support.

**Comment by edzer** [comment]
Great news, @jeroen  - thanks a lot; I look forward to getting this tested!

**Comment by jeroen** [comment]
@mdsumner do you still need/use kealib? I don't see this driver in any other operating system (ubuntu, macos), so I'm considering to drop it for the next release.

**Comment by mdsumner** [comment]
I don't but @pierreroudier might

**Comment by pierreroudier** [comment]
@jeroen Using it occasionally, typically one would compile the driver separately and it would be added to the list of available drivers: 

https://gdal.org/drivers/raster/kea.html

**Comment by jeroen** [comment]
@pierreroudier do you use the windows builds, or do you compile yourself on linux?

**Comment by pierreroudier** [comment]
@jeroen compiling by myself on Linux.
